apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orbital-tracker-ingress
  namespace: orbital-tracker
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80
