"""add group column to satellites

Revision ID: e59027529363
Revises: e33e83f118d6
Create Date: 2026-04-22 00:15:11.586244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59027529363'
down_revision: Union[str, None] = 'e33e83f118d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('satellites', sa.Column('group', sa.String(), nullable=True))
    op.execute("UPDATE satellites SET \"group\" = 'stations' WHERE \"group\" IS NULL")
    op.alter_column('satellites', 'group', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('satellites', 'group')
    # ### end Alembic commands ###
